import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "룩말 스토리랩",
  description: "Generated by create next app",
};

const yui = localFont({
  src: "../public/fonts/NanumGimYuICe.ttf",
  variable: "--font-yui",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={
          yui.className +
          " h-dvh overflow-auto break-keep leading-relaxed text-2xl lg:text-4xl px-8 lg:px-24 antialiased bg-[url('/bg.png')] bg-cover"
        }
        style={{ height: "100dvh" }}
      >
        {children}
      </body>
    </html>
  );
}
