import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-[Yui] break-keep leading-relaxed text-2xl lg:text-4xl px-10 lg:px-24 antialiased min-h-screen bg-[url('/bg.png')] bg-cover">
        {children}
      </body>
    </html>
  );
}
